export const ACTIONS_FILL_SUBMISSION_START = 'ACTIONS_FILL_SUBMISSION_START';
export const ACTIONS_FILL_SUBMISSION_FINISH = 'ACTIONS_FILL_SUBMISSION_FINISH';
export const ACTIONS_CREATE_JOURNAL = 'ACTIONS_CREATE_JOURNAL';

export const ACTIONS_EDIT_CATEGORIES_START = 'ACTIONS_EDIT_CATEGORIES_START';
export const ACTIONS_EDIT_CATEGORIES_FINISH = 'ACTIONS_EDIT_CATEGORIES_FINISH';
export const ACTIONS_ADD_CATEGORY = 'ACTIONS_ADD_CATEGORY';
export const ACTIONS_REMOVE_CATEGORY = 'ACTIONS_REMOVE_CATEGORY';
export const ACTIONS_UPDATE_CATEGORY = 'ACTIONS_UPDATE_CATEGORY';

export const ACTIONS_CREATE_EDITION = 'ACTIONS_CREATE_EDITION';

export const ACTIONS_FILTER_BY_CATEGORY = 'ACTIONS_FILTER_BY_CATEGORY';

export const ACTIONS_ARCHIVE_START = 'ACTIONS_ARCHIVE_START';
export const ACTIONS_ARCHIVE_SET_YEAR = 'ACTIONS_ARCHIVE_SET_YEAR';
export const ACTIONS_ARCHIVE_SET_MONTH = 'ACTIONS_ARCHIVE_SET_MONTH';
// export const ACTIONS_ARCHIVE_UPDATE_FILTER ='ACTIONS_ARCHIVE_UPDATE_FILTER';
export const ACTIONS_LOAD_EDITION = 'ACTIONS_LOAD_EDITION';
export const ACTIONS_BACK_TO_CURRENT = 'ACTIONS_BACK_TO_CURRENT';

export const ACTIONS_SEARCH_START = 'ACTIONS_SEARCH_START';
export const ACTIONS_SEARCH_SUBMIT = 'ACTIONS_SEARCH_SUBMIT';
export const ACTIONS_SEARCH_PAGINATE = 'ACTIONS_SEARCH_PAGINATE';

export const ACTIONS_REACT_ON_ARTICLE = 'ACTIONS_REACT_ON_ARTICLE';
export const ACTIONS_REACT_ON_ARTICLE_ADD = 'ACTIONS_REACT_ON_ARTICLE_ADD';
export const ACTIONS_REACT_ON_ARTICLE_REMOVE = 'ACTIONS_REACT_ON_ARTICLE_REMOVE';

export const ACTIONS_ARTICLE_DETAILS = 'ACTIONS_ARTICLE_DETAILS';
export const ACTIONS_ARTICLE_REVIEWS_START = 'ACTIONS_ARTICLE_REVIEWS_START';
export const ACTIONS_ARTICLE_SHARE_START = 'ACTIONS_ARTICLE_SHARE_START';

export const ACTIONS_ARTICLE_SHARE_CHANGE = 'ACTIONS_ARTICLE_SHARE_CHANGE';

export const ACTIONS_EDITION_PAGINATE = 'ACTIONS_EDITION_PAGINATE';

export const ACTIONS_HOME_MAIN_OPTIONS = 'ACTIONS_HOME_MAIN_OPTIONS'
export const ACTIONS_PREFERENCES_START = 'ACTIONS_PREFERENCES_START';
export const ACTIONS_PREFERENCES_SUBMIT = 'ACTIONS_PREFERENCES_SUBMIT';
export const ACTIONS_SETTINGS_START = 'ACTIONS_SETTINGS_START';
export const ACTIONS_SETTINGS_SUBMIT = 'ACTIONS_SETTINGS_SUBMIT';
export const ACTIONS_REWARDS_START = 'ACTIONS_REWARDS_START';

export const ACTIONS_PUBLISH_NEW_EDITION = 'ACTIONS_PUBLISH_NEW_EDITION';
