export const FIELDS_SEARCH_PHRASE = 'FIELDS_SEARCH_PHRASE'
export const FIELDS_SELECTED_CONVERSATION = 'FIELDS_SELECTED_CONVERSATION'

export const FIELDS_JOURNAL_TITLE = 'FIELDS_JOURNAL_TITLE';
export const FIELDS_JOURNAL_PUBLISH_DAY = 'FIELDS_JOURNAL_PUBLISH_DAY';
export const FIELDS_JOURNAL_PUBLISH_TIME = 'FIELDS_JOURNAL_PUBLISH_TIME';
export const FIELDS_PREFERENCES_HIDDEN_TOPICS = 'FIELDS_PREFERENCES_HIDDEN_TOPICS'
export const FIELDS_PREFERENCES_WEEKLY_QUOTA = 'FIELDS_PREFERENCES_WEEKLY_QUOTA'

export const FIELDS_SUBMISSION_URL = 'FIELDS_SUBMISSION_URL';
export const FIELDS_SUBMISSION_RECOMMENDATION = 'FIELDS_SUBMISSION_RECOMMENDATION';
export const FIELDS_SUBMISSION_CATEGORIES = 'FIELDS_SUBMISSION_CATEGORIES';
